### ISSUE TITLE
Upstream times out on preemptible/spot machines due to Terminated Pods (GKE)

### ISSUE THREAD

**Issue by gardun0** [kumahq/kuma#3728] opened 2022-01-18 19:22 UTC
### What happened?

Hello,

- **GKE Version:** 1.21.5-gke.1302
- **Kuma Version:** 1.4.1

I have this situation where the upstream times out, this is caused in a scenario where i use preemptible/spot VMs so once they're requested, Pods within the Nodes are gracefully terminated, now, the Workload has for example 1 pod running and 9 with status Terminated. This is the normal scenario, from Kuma this services are "partially degraded" and this makes upstream times out a lot.

As a workaround i did a cron job which fully deletes Terminated pods, but this scenario is normal for Kuma?

Regards.

**Comment by lahabana** [comment] 2022-01-19 15:57
That's a good question. We might want to delete Dataplanes for terminated pods in Kuma.
@bartsmykla @jakubdyszkiewicz WDYT?

**Comment by lahabana** [comment] 2022-01-24 15:12
The partially degraded state is correct. However, it's not normal you are getting time outs as the pods that are terminated shouldn't be in the list of endpoints for xds.
Someone, from the team will try to reproduce and look at what happens.

**Comment by lobkovilya** [comment] 2022-01-25 10:16
@gardun0 we have a `health.ready` status set automatically for every inbound and that should prevent the behaviour you observe. But for some reason it didn't kick in and I'm trying to figure out why. The only valid reason why this status could be omitted on Kubernetes is the lack of [containerPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#containerport-v1-core) in Pod's container specification (in that case we can't match which container implements what service). 

Could you please check your Deployment and see if there is containerPort?

**Comment by lahabana** [comment] 2022-03-17 12:46
@gardun0 any update there?

**Comment by lahabana** [comment] 2022-04-25 08:22
Closing this due to lack of answer from the opener

**Closed by lahabana** 2022-04-25 08:22 UTC
Labels: triage/needs-information, triage/rotten, kind/bug
