### ISSUE TITLE
 Kuma-DP Image Pull Issue from private registry

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#11179] opened 2024-08-23 05:10 UTC
### What happened?

Hi Team,

We are trying to use a private registry for Kuma images. Although, the Kuma control plane images are being successfully pulled using the imagePullSecret specified in the Helm chart, we're encountering an issue with the Kuma-DP images for the DP proxy in the application pod. These images are failing to pull due to a missing imagePullSecret.

We attempted to use a container patch to add the imagePullSecret as suggested, but it didn't work since imagePullSecret is a pod-level configuration, not applicable at the sidecar container level. 
Reference: https://github.com/kumahq/kuma/issues/10944

Could you please guide how to resolve this issue?

Thank you.

**Comment by bartsmykla** [comment] 2024-08-26 14:12
Duplicate of: https://github.com/kumahq/kuma/issues/10944

**Closed by bartsmykla** 2024-08-26 14:12 UTC
Labels: triage/duplicated, kind/bug
