### ISSUE TITLE
Configure levels of specific loggers

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4446] opened 2022-06-08 11:31 UTC
### Description

We need to have a system to adjust a log level for the specific logger.
It's important for systems that are shipped to users. Without that, adjusting the logging required a new release.
We try our best to pick a proper level, but we may pick the wrong level and have
* missing observability by default
* spamming the logging infrastructure

go-logr and zap do not have a system like that by default.

Configuration can be via cli or by API calls in the runtime (nice to have)

Charly note: if we do this by API we need to call 5 instances (or X) to change it for every instance

**Comment by slonka** [comment] 2023-06-23 07:36
> go-logr and zap do not have a system like that by default.

I'm not sure I understand the "default" part of this sentence. Zap has [AtomicLevel](https://pkg.go.dev/go.uber.org/zap#AtomicLevel) where you can set the log level, what we'd need to do is store this for every logger that we create and then expose an endpoint to set it individually. A PoC that set's it for all loggers is here: https://github.com/kumahq/kuma/compare/master...slonka:kuma:dynamic-log-level?expand=1#diff-8ee5e904442d62cebde1e84550f08579152de442c32f0f90fb4bcd793ecbe8f5R11 

Let me know if this is what you had in mind.

**Comment by jakubdyszkiewicz** [comment] 2023-07-06 14:26
> I'm not sure I understand the "default" part of this sentence

I something like slf4j.

Yes, exactly, we would need to somehow store it for every logger we create. In your PoC I see dynamic logging level change for all loggers. That's ok, but more important part of this issue is level for specific loggers. I consider configuring it via HTTP API rather optional. More important is to configure this via cli, because it can survive restart.

**Comment by lahabana** [comment] 2024-05-15 07:15
Duplicate of: https://github.com/kumahq/kuma/issues/10230

**Closed by lahabana** 2024-05-15 07:15 UTC
Labels: triage/accepted, kind/feature
