### ISSUE TITLE
why not implement the gateway. base on envoy.  no need kong/nginx thirdparty gateway 

### ISSUE THREAD

**Issue by huo4444** [kumahq/kuma#1164] opened 2020-11-17 06:33 UTC
why not implement the gateway. base on envoy.  no need kong/nginx thirdparty gateway

**Comment by rucciva** [comment] 2020-12-04 04:04
Agreed. This will add one more use case possible for Kuma, a distributed API gateway.

**Comment by lahabana** [comment] 2021-12-17 09:29
Duplicate of #3300

**Closed by lahabana** 2021-12-17 09:29 UTC
Labels: kind/feature
