### ISSUE TITLE
Support MeshTCPRoute in MeshGateway

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6948] opened 2023-06-07 08:31 UTC
### Description

This will enable us to deprecate MeshGatewayRoute in favour of the more standard MeshHTTPRoute and MeshTCPRoute.

Can the route and cluster generation code actually be reused for both gateway and non gateway code?

**Comment by lahabana** [comment] 2023-06-07 08:32
xref #6847

**Comment by michaelbeaumont** [comment] 2023-10-25 09:06
Duplicate of https://github.com/kumahq/kuma/issues/8142

**Closed by michaelbeaumont** 2023-10-25 09:06 UTC
Labels: triage/accepted, kind/feature, area/policies, area/gateway
