### ISSUE TITLE
Consider periodically disconnecting DPPs from the CP to evenly distribute the streams

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#10845] opened 2024-07-09 14:40 UTC
### Description

So we don't end up with unevenly distributed number of XDS streams indefinitely like this:

<img width="236" alt="image" src="https://github.com/kumahq/kuma/assets/2753650/b560f862-f917-4d22-941c-9ea4ef176547">

**Comment by jakubdyszkiewicz** [comment] 2024-07-09 15:02
duplicate of https://github.com/kumahq/kuma/issues/4039

**Closed by jakubdyszkiewicz** 2024-07-09 15:02 UTC
Labels: triage/pending, kind/improvement
