### ISSUE TITLE
Install Kong Gateway 2.5 with kumactl 1.3.x 

### ISSUE THREAD

**Issue by gAmUssA** [kumahq/kuma#2807] opened 2021-09-21 03:55 UTC
### Summary

Currently, `kumactl install gateway` installs kong 2.4

### Steps To Reproduce

1. `kumact install gateway kong | kubectl apply -f`
2.
3.
4.

### Additional Details & Logs

- Version
❱ kumactl version
Kuma: 1.3.0
- Error logs
- Configuration
- Platform and Operating System
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)
Kubernetes, `kumactl install control-plane`

**Comment by jpeach** [comment] 2021-09-21 03:57
ping @subnetmarco

**Comment by subnetmarco** [comment] 2021-09-21 04:23
@kumahq/kuma-maintainers we need to add a reminder to update this and other dependencies on every major release.

**Comment by lahabana** [comment] 2021-09-21 07:27
Is there maybe a way for dependabot to have this integrated?

**Comment by jpeach** [comment] 2021-11-03 00:15
Per #3066, Kuma should install Kong 2.6 and KIC 2.0.

**Comment by lahabana** [comment] 2021-11-29 13:41
Dupe of: #3377

**Closed by lahabana** 2021-11-29 13:41 UTC
Labels: area/kumactl, triage/duplicated, kind/improvement, area/installation
