### ISSUE TITLE
Can't run sidecar when "automountServiceAccountToken" is set to false.  Any alternatives?

### ISSUE THREAD

**Issue by jbehrends** [kumahq/kuma#4029] opened 2022-03-21 21:19 UTC
### Description

Hello!

Running in K8s
Deployed and configured using kong-mesh (Kuma) helm chart.

My company uses OPA/Gatekeeper to enforce security policies via the OPA/Gatekeeper admission controller.   One of the global deny policies that we have deployed is all deployments/pods/etc must have automountServiceAccountToken set to "false".  As a result if we want to get the service mesh sidecar to work, we need to get an exception to not set automountServiceAccountToken to false..  
Otherwise we get the following error, and the sidecar just goes into a crashloop forever:
```
Error: could not read file /var/run/secrets/kubernetes.io/serviceaccount/token: stat /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

So I'm curious if there is a way to configure the injected sidecar to manually mount the default service account token, or any other options at all other than leaning on the auto mounting of the default service account token?

Thanks for any suggestions!

**Comment by jakubdyszkiewicz** [comment] 2022-03-22 08:06
https://kuma.io/docs/1.5.x/security/dp-auth/#service-account-token

Service Account Token is used for authentication of the data plane proxy in the control plane.
You can disable authentication with is of course insecure and not production-ready.

The other alternative is to use Dataplane Token. However, I don't think we tested it with a Kubernetes setup. Using instead of Service Account Token it means that you will need to do extra operational work (issuing and distributing tokens) so people are usually not interested in it.

What is the reason that you cannot use the service account token in your environment?

**Comment by gauravdasson** [comment] 2022-03-23 05:00
The problem is not that service account token can not be used. The problem is that the context is too broad since the spec is applied at a pod level. This literally provides every Pod that runs with Kong Mesh automount their tokens, even if it is not needed, Not giving every pod that liberty is what is required by company's security policy.

Would it be possible for kuma to inject the service account token into the dataplane container only through the use of projected volumes? 
Ex: https://kubernetes.io/docs/concepts/storage/projected-volumes/
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#serviceaccount-admission-controller – see Bound Service Account Token Volume

**Comment by jakubdyszkiewicz** [comment] 2022-03-24 14:54
Thanks for providing more context!

AFAIK @johnharris85 is working on support SAT that are mounted to one container only.

As for projected tokens with a short expiration time, it's not a trivial change since the token is read on the Bootstrap phase of Envoy so we would need to restart Envoy to read it again.

**Comment by johnharris85** [comment] 2022-04-04 16:00
I think this is fixed, we can probably close @lahabana @jakubdyszkiewicz? 

I've opened https://github.com/kumahq/kuma/issues/4121 to track supporting projected service account tokens.

**Comment by jakubdyszkiewicz** [comment] 2022-04-05 08:06
Make sense to close this and track PSAT as a separate ticket, thanks.

**Closed by jakubdyszkiewicz** 2022-04-05 08:06 UTC
Labels: triage/accepted, kind/feature
