### ISSUE TITLE
Support Gateway functionality on a regular dataplane

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#2614] opened 2021-08-19 16:43 UTC
On universal mode gateway functionality is achieved by adding a new gateway dataplane. This requires a new set of resources for gateway to be managed. 

If the gateway functionality is developed in such a way that any dataplane can be converted into a gateway, additional resources to manage the gateway can be removed.

**Comment by lahabana** [comment] 2021-11-29 14:29
@jpeach can you confirm that we're actually taking an approach that's quite different from this? Gateway is getting more specific and it will be not possible to transform an existing dp in a gateway?

**Comment by jpeach** [comment] 2021-11-29 23:00
Gateway is an existing DP with a specific configuration. So I *think* that is close enough to what we are talking about here?

**Comment by jpeach** [comment] 2021-12-07 00:16
triage: marking as duplicate, please re-open if this is not correct

Duplicate of #3300

**Comment by jpeach** [comment] 2021-12-07 00:17
Duplicate of #3300

**Closed by jpeach** 2021-12-07 00:16 UTC
Labels: area/universal, kind/feature, area/gateway
