### ISSUE TITLE
(Bug) : External services details are not populating in GUI after certain limits

### ISSUE THREAD

**Issue by adarsh-padhi** [kumahq/kuma#9293] opened 2024-02-18 06:42 UTC
## Summary

Details of External services is not being populated in GUI after a certain limit. The ext-svc details are populated till 100th ext-svc and all details can be seen from GUI .Post 100th ext-svc, when we click on the ext-svc details , it shows blank page . 

Attaching Screenshot for more clarity.
<img width="1777" src="https://github.com/kumahq/kuma/assets/98748492/19792168-85d6-4f95-aa50-c4b7c905a783">
 
 
## Steps to reproduce the issue

- Create 101 number of ext-svc
- Check the details of the 100th ext-svc in the UI in **Services** tab , You will be able to see the details of ext-svc
- Then Check the 101th ext-svc , & you will able to see that no details will be populating

## Kuma Version

2.4.1

## Findings

As per my findings , kuma API ```/meshes/{mesh}/external-services```  returns the first 100 ext-svc name sorted in alphabetically order and at the last it will say to use ```offset``` parameter to see the next 100 elements. 

I checked the frontend & I see the above API is being used to get the details of the ext-svc , Since only the default parameters are being called , only the first 100 values are populated in GUI , leaving this to raise a bug

If kuma team can fix this it would be a grateful.

**Comment by jakubdyszkiewicz** [comment] 2024-02-19 15:08
> Triage: let's try to reproduce, also try with other resources

**Comment by adarsh-padhi** [comment] 2024-02-21 09:09
@jakubdyszkiewicz  , @bartsmykla I tried the same with traffic permission & Trafficroute policies , both are working fine in UI

**Comment by bartsmykla** [comment] 2024-02-21 11:43
I was able to reproduce the issue on 2.4.1, but it seems it's not happening on 2.6.1. It seems to me it's a UI issue though

https://github.com/kumahq/kuma/assets/11655498/d9639a9d-3f96-4ba1-948f-35880afc6503

**Comment by kleinfreund** [comment] 2024-02-21 12:08
Here’s what happens:

- In the service list view, we list ServiceInsight objects. This is working correctly.
- In the service detail view, when clicking on an entry for a ServiceInsight object with `serviceType: external`, we still fetch the ServiceInsight object first (you see this in the network tab in Bart’s recording)
- In response to that, we also query the `/meshes/:mesh/external-services` API and try to find **the ExternalService which has a `kuma.io/service` tag with the name of the ServiceInsight object** in the response. We can’t just query `/meshes/:mesh/external-services/:name-of-service-insight` because ServiceInsight and ExternalService names are not the same.
- This breaks if the response from the ExternalService list API doesn’t contain the corresponding ExternalService. This in turn happens when one has "too many" ExternalService as to exceed the pagination limits of that API (I assume that limit is 100 here?)

As far as I’m aware, the Kuma API in 2.4.x doesn’t support a `tag` query parameter on the `/meshes/:mesh/external-services` API. We could otherwise use this to query directly for the ExternalServices that have the desired `kuma.io/service` tag.

Not sure what we can do here beyond that.

Besides this issue of not being able to find the right ExternalService, we can at the very least stop this view from crashing and display a message instead that we couldn’t find the right thing.

**Comment by johncowen** [comment] 2024-02-21 12:13
Question: is this the `null` we are encountering?

https://github.com/kumahq/kuma-gui/blob/release-2.4/src/services/kuma-api/KumaApi.ts#L208

**Comment by kleinfreund** [comment] 2024-02-26 14:44
https://github.com/kumahq/kuma-gui/pull/2218 was merged which addresses the following:

- When the UI isn’t able to find the right ExternalService, we show an appropriate message now instead of the UI breaking as shown in the screenshot above and errors appearing in the console
- We now do the lookup of the matching ExternalService using a `size` parameter with the value `1000`. Effectively, this will solve this problem for users with 1000 ExternalServices or fewer.

On the side of the UI, we can’t truly prevent the issue from happening though. To do so, the `/meshes/:mesh/external-services` API would need to support `tag` filter parameters as it does in newer versions of Kuma. Then, the UI lookup would always find the correct ExternalService. To that end, the PR also made sure to send the `tag` parameter proactively.

**Comment by jakubdyszkiewicz** [comment] 2024-02-26 15:28
> Triage: fixed in the release branch of 2.4. It will be fixed in 2.4 whenever we release a patch version. It's fixed in 2.5 or later

**Closed by jakubdyszkiewicz** 2024-02-26 15:28 UTC
Labels: triage/accepted, kind/bug
