### ISSUE TITLE
Validate TCP route in MeshGatewayRoute

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4844] opened 2022-08-17 15:00 UTC
### What happened?

This MeshGatewayRoute is considered valid by CP
```
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: default
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kuma.io/v1alpha1","kind":"MeshGatewayRoute","mesh":"default","metadata":{"annotations":{},"name":"edge-gateway-route"},"spec":{"conf":{"http":{"rules":[{"backends":[{"destination":{"kuma.io/service":"demo-app_kuma-demo_svc_5000"}}],"matches":[{"path":{"match":"PREFIX","value":"/"}}]}]}},"selectors":[{"match":{"kuma.io/service":"edge-gateway","port":"http/8080"}}]}}
  creationTimestamp: "2022-08-17T14:52:53Z"
  generation: 2
  name: edge-gateway-route
  ownerReferences:
  - apiVersion: kuma.io/v1alpha1
    kind: Mesh
    name: default
    uid: 60890cf9-f436-4ebc-ade8-7416f2b4f426
  resourceVersion: "79179"
  uid: 49440297-3053-4af3-a19c-b75519d0ebf9
spec:
  conf:
    tcp:
      rules:
      - backends:
        - destination:
            kuma.io/service: demo-app_kuma-demo_svc_5000
        matches:
        - path:
            match: PREFIX
            value: /
  selectors:
  - match:
      kuma.io/service: edge-gateway
      port: http/8080
```

but I don't think `tcp` section should allow HTTP matches.

**Comment by jakubdyszkiewicz** [comment] 2022-08-17 15:14
It causes
```
2022-08-17T15:13:32.737Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"default","Name":"edge-gateway-6b9dc87456-6ch54.kuma-demo"}, "error": "invalid resource \"edge-gateway:HTTP:8080\": invalid RouteConfiguration.VirtualHosts[0]: embedded message failed validation | caused by: invalid VirtualHost.Routes[0]: embedded message failed validation | caused by: invalid Route.Match: embedded message failed validation | caused by: invalid RouteMatch.PathSpecifier: value is required", "errorVerbose": "invalid RouteConfiguration.VirtualHosts[0]: embedded message failed validation | caused by: invalid VirtualHost.Routes[0]: embedded message failed validation | caused by: invalid Route.Match: embedded message failed validation | caused by: invalid RouteMatch.PathSpecifier: value is required\ninvalid resource \"edge-gateway:HTTP:8080\"\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220817060923-79a13d5572bb/pkg/xds/server/v3/reconcile.go:83\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220817060923-79a13d5572bb/pkg/xds/sync/dataplane_watchdog.go:128\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220817060923-79a13d5572bb/pkg/xds/sync/dataplane_watchdog.go:65\ngithub.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220817060923-79a13d5572bb/pkg/xds/sync/dataplane_watchdog_factory.go:45\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220817060923-79a13d5572bb/pkg/util/watchdog/watchdog.go:25\nruntime.goexit\n\t/home/circleci/go/src/runtime/asm_amd64.s:1571"}
```

**Comment by michaelbeaumont** [comment] 2022-08-23 18:38
@jakubdyszkiewicz I can't reproduce this error. It may be that you had the `MeshGateway` set to `protocol: HTTP`, which has been fixed by https://github.com/kumahq/kuma/pull/4841 and the build you used may not have included it?  

The fact that that we allow unknown fields in our resources means that it's impossible to prevent users from creating resources like this.

The resource Kuma sees, however, has:

```
message TcpRoute {
 message Match {};
 message Rule {
   repeated Match matches = 1;
...
```

so the prefix match shouldn't actually cause any errors.

**Comment by michaelbeaumont** [comment] 2022-08-31 00:33
@jakubdyszkiewicz I'll close this, let me know if you think it's still an issue

**Closed by michaelbeaumont** 2022-08-31 00:33 UTC
Labels: triage/accepted, triage/needs-information, kind/bug
