### ISSUE TITLE
Reachable Service with MeshService

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#9709] opened 2024-03-25 13:53 UTC
### Description

MADR + implementation
```[tasklist]
### Tasks
```

**Comment by lahabana** [comment] 2024-07-24 09:46
@lukidzi you've done this no?

**Comment by lahabana** [comment] 2024-07-24 15:58
Duplicate of https://github.com/kumahq/kuma/issues/10508

**Closed by lahabana** 2024-07-24 15:58 UTC
Labels: triage/accepted, kind/feature
