### ISSUE TITLE
Add warnings in policy matching inspect API

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8327] opened 2023-11-13 10:02 UTC
### Description

We should be able to do contextual validation when doing policy matching to show warnings and errors. This would then be exposed in the inspect API and can be easily shown in the UI.

For example:

- using a policy or a config which required mTLS to be enabled
- using zoneEgress on a feature that has limitations...

This would be a good improvement of our UX

This would be a path to do: https://github.com/kumahq/kuma/issues/3734

**Comment by jakubdyszkiewicz** [comment] 2023-11-13 15:05
duplicate of https://github.com/kumahq/kuma/issues/5870

**Closed by jakubdyszkiewicz** 2023-11-13 15:05 UTC
Labels: triage/accepted, kind/feature, area/policies
