### ISSUE TITLE
Telemetry for kubernetes client perf

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6972] opened 2023-06-08 07:22 UTC
### Description

Issues like: https://github.com/kumahq/kuma/pull/6951 could have more easily diagnosed with good client metrics on our controllers and matching data in the prom dashboard.

**Comment by lahabana** [comment] 2023-06-08 14:19
xref #6945

**Comment by jakubdyszkiewicz** [comment] 2023-06-12 14:39
duplicate of https://github.com/kumahq/kuma/issues/2927

**Closed by jakubdyszkiewicz** 2023-06-12 14:39 UTC
Labels: area/observability, triage/pending, kind/feature
