### ISSUE TITLE
Need a way to enable dns logging/debugging

### ISSUE THREAD

**Issue by timothy-spencer** [kumahq/kuma#8254] opened 2023-11-03 23:49 UTC
### Description

As somebody who is trying to set up a mesh in kubernetes and run terraform in it, I need a way to turn on coredns query logging or debugging on, so that I can use the logs from that to enumerate all the external services that I need to allow outbound access to.

I have tried editing the running kuma-sidecar Corefile to add dump/log/debug, and then sending a SIGHUP to coredns, but stdout seems to not be going to the same stdout as the envoy/dp stuff.  Either that, or I don't know how to turn on logging properly, or I'm not allowed to SIGHUP it or something.

In any case, either some documentation on the proper way to do this, or even better, some sort of option in the helm chart that will enable query logging would be REALLY useful to people trying to debug this sort of thing.

Thanks, and have fun!

**Comment by lahabana** [comment] 2023-11-06 14:47
Duplicate of https://github.com/kumahq/kuma/issues/5516

**Closed by lahabana** 2023-11-06 14:47 UTC
Labels: triage/duplicated, kind/feature
