### ISSUE TITLE
In rare cases dataplane might not be connected to the CP and will result in degraded connection 

### ISSUE THREAD

**Issue by albertpx** [kumahq/kuma#6653] opened 2023-05-01 20:15 UTC
### What happened?

We are running a universal multi-zone cluster.

In some rare cases, which unfortunately I'm unable to identify when exactly, a dataplane might not be really connected to the control plane, and will show the following logs:
```
2023-05-01T19:37:53.239290000Z [2023-05-01 19:37:53.239][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 126 ms.
2023-05-01T19:38:23.449237000Z [2023-05-01 19:38:23.448][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:38:23.450779000Z [2023-05-01 19:38:23.450][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 655 ms.
2023-05-01T19:38:54.208380000Z [2023-05-01 19:38:54.207][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:38:54.209334000Z [2023-05-01 19:38:54.208][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 952 ms.
2023-05-01T19:39:25.254179000Z [2023-05-01 19:39:25.253][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:39:25.254687000Z [2023-05-01 19:39:25.253][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 519 ms.
2023-05-01T19:39:55.862140000Z [2023-05-01 19:39:55.861][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:39:55.863509000Z [2023-05-01 19:39:55.863][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 160 ms.
2023-05-01T19:40:26.111159000Z [2023-05-01 19:40:26.110][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:40:26.111761000Z [2023-05-01 19:40:26.110][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 556 ms.
2023-05-01T19:40:56.757305000Z [2023-05-01 19:40:56.757][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:40:56.758805000Z [2023-05-01 19:40:56.758][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 282 ms.
2023-05-01T19:41:27.134231000Z [2023-05-01 19:41:27.133][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:41:27.134791000Z [2023-05-01 19:41:27.133][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 341 ms.
2023-05-01T19:41:57.564023000Z [2023-05-01 19:41:57.563][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:41:57.569147000Z [2023-05-01 19:41:57.568][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 101 ms.
2023-05-01T19:42:27.763258000Z [2023-05-01 19:42:27.762][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:42:27.763989000Z [2023-05-01 19:42:27.762][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 30 ms.
2023-05-01T19:42:57.882509000Z [2023-05-01 19:42:57.882][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:42:57.883024000Z [2023-05-01 19:42:57.882][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 472 ms.
2023-05-01T19:43:28.447700000Z [2023-05-01 19:43:28.447][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:43:28.448482000Z [2023-05-01 19:43:28.447][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 760 ms.
2023-05-01T19:43:59.298442000Z [2023-05-01 19:43:59.297][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:43:59.299017000Z [2023-05-01 19:43:59.297][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 461 ms.
2023-05-01T19:44:29.850089000Z [2023-05-01 19:44:29.849][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:44:29.850764000Z [2023-05-01 19:44:29.849][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 790 ms.
2023-05-01T19:45:00.724175000Z [2023-05-01 19:45:00.723][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:45:00.725374000Z [2023-05-01 19:45:00.725][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 833 ms.
2023-05-01T19:45:31.655741000Z [2023-05-01 19:45:31.655][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
2023-05-01T19:45:31.657166000Z [2023-05-01 19:45:31.656][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:67] HdsDelegate stream/connection failure, will retry in 102 ms.
2023-05-01T19:46:01.844989000Z [2023-05-01 19:46:01.844][38][warning][upstream] [source/common/upstream/health_discovery_service.cc:322] StreamHealthCheck gRPC config stream closed: 2, dataplane not found. Create Dataplane in Kuma CP first or pass it as an argument to kuma-dp
```

The service using this dataplane, will be able to send only some of the requests - about half of them will result in a timeout.

On the control plane side, the dataplane does not exist - either by looking at the gui via the global cp or via `kumactl get dataplanes` of the zone cluster.

In our case, this happened to a service running a single instance of an outbound dataplane - so the whole service was basically down until we restarted that instance.

It appears that the dataplane should try reconnecting/re-registering to the control plane, but it never does.
Can the dataplane at the very least detect such an issue as indicated in the log above and try to reconnect/re-register to the control plane?

**Comment by jakubdyszkiewicz** [comment] 2023-05-02 13:31
> Triage: this might be caused by https://github.com/kumahq/kuma/pull/6568 @lobkovilya will double-check. Do you have a single instance of the control plane?

**Comment by bartsmykla** [comment] 2023-05-18 08:39
Hi @albertpx, would you be able to try if [this fix](https://github.com/kumahq/kuma/pull/6568) maybe resolve the issue you mentioned?

You could try to install the latest version from master, i.e.:
```sh
curl -L https://kuma.io/preview.sh | sh -
```
This command will download latest binaries to directory similar to `kuma-0.0.0-preview.v19d31b966` where `19d31b966` is the hash of the latest commit available for preview. You can use the binaries under `kuma-0.0.0-preview.v{hash}/bin/` like a regular binaries. I.e. to install control plane you could do:
```sh
./kuma-0.0.0-preview.v{hash}/bin/kumactl install control-plane | kubectl apply -f-
```
and it would install control-plane using appropriate image versions

**Comment by albertpx** [comment] 2023-05-18 08:57
Unfortunately no, because so far the issue has not been replicated, and I do not know how to replicate it.

**Comment by bartsmykla** [comment] 2023-05-18 10:08
@albertpx if you will encounter this again, please get back to us. Could you write if between the last time you saw it happened and now you updated version of kuma maybe? Also, for how long it has not been replicated?

**Comment by jakubdyszkiewicz** [comment] 2023-12-18 12:51
Closing because of no information in 7 months. Feel free to reopen this, but we need much more information, because we could not reproduce this. Info like
* CP logs (ideally debug level)
* DP logs (full)
* Events occurring this time in the environment (scaling up down pods, nodes)

Thank you

**Closed by jakubdyszkiewicz** 2023-12-18 12:51 UTC
Labels: triage/rotten, kind/bug
