### ISSUE TITLE
TrafficLog v2 

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2007] opened 2021-05-19 16:13 UTC
### Summary

I'd like to use a TrafficLog policy (i.e. Envoy Access Logging) to enable access logs for destination services/DPPs. Currently only source DPPs are enabled for access logging via a TrafficLog policy. 

Only outbound listeners are configured for access logging. 

### Steps To Reproduce

Note in the attached config_dump that inbound:echo-service_default_svc_8080 is not configured for access logging while all outbound listeners have access logging configured. 

[config_dump.txt](https://github.com/kumahq/kuma/files/6510252/config_dump.txt)

**Comment by jakubdyszkiewicz** [comment] 2021-07-02 12:17
xref #271

**Comment by lahabana** [comment] 2022-05-30 12:32
The new version of traffic log should support both inbound and outbound trafficLog.

**Comment by lahabana** [comment] 2022-08-02 12:22
Duplicate of #4733

**Closed by lahabana** 2022-08-02 12:22 UTC
Labels: triage/accepted, kind/design
