### ISSUE TITLE
Enhance MeshGatewayInstance to allow specification of additional Deployment fields

### ISSUE THREAD

**Issue by conman2305** [kumahq/kuma#5257] opened 2022-11-02 20:50 UTC
### Description

Currently, the MeshGatewayInstance CRD allows us to specify the number of replicas and resources for the pods, but other things like annotations and affinity rules can't be set. I'm sure there are other fields that other people might want to set in the Deployment object, so it'd be cool if the CRD could have `deploymentTemplate` and `podTemplate` sections similar to the existing `serviceTemplate` section so that the `spec` field could be set wholesale at both the Pod and Deployment level

(Other than that, I am LOVING the MeshGatewayInstance setup in Kuma. This was _the_ feature that had us select Kuma over any other service mesh. So THANK YOU to all the contributors who work on this amazing product.)

**Comment by michaelbeaumont** [comment] 2022-11-02 21:01
Thanks for the feedback! If you're interested checkout [the Gateway API support](https://kuma.io/docs/1.8.x/explore/gateway-api/)!

Duplicate of https://github.com/kumahq/kuma/issues/5027

**Comment by michaelbeaumont** [comment] 2022-11-02 21:02
Duplicate of https://github.com/kumahq/kuma/issues/5027

**Closed** 2022-11-05 09:26 UTC
Labels: triage/duplicated, kind/feature
