### ISSUE TITLE
Add function to validate if iptables were properly applied on universal

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#10303] opened 2024-05-22 17:07 UTC
### Description

It would be nice if we had an option to validate whether iptables rules were applied correctly on a VM. We have a similar feature for CNI that works on universal, but it requires running as a specific user. If we agree on this approach, we should document that it needs to be run as a particular user.
```
runuser -u kuma-dp -- ./kumactl install transparent-proxy-validator --no-config
```

Would be nice to have something simpler
```
kumactl status transparent-proxy
```

**Comment by jakubdyszkiewicz** [comment] 2024-05-27 14:04
Duplicate of https://github.com/kumahq/kuma/issues/8414

**Closed by jakubdyszkiewicz** 2024-05-27 14:04 UTC
Labels: area/kumactl, triage/pending, kind/feature
