### ISSUE TITLE
New option to change the log level of CoreDNS in the sidecar

### ISSUE THREAD

**Issue by bcollard** [kumahq/kuma#8151] opened 2023-10-26 09:57 UTC
### Description

Looking for an easy way to enable logging in the CoreDNS instance of the kuma-sidecar.

Can be with:
- a new annotation / env var
- re-using an existing annotation like `kuma.io/sidecar-env-vars` and a new env var
- associated with existing flags, like the log-level in `kuma-dp run` 
- [custom coredns templates](https://github.com/kumahq/kuma/issues/8119)
- something else

EDIT: just so we remember, ContainerPatch didn't help. I can mount a volume on the sidecar, but I can't create a new volume on the pod, which would contain the CoreDNS customized template.

**Comment by jakubdyszkiewicz** [comment] 2023-10-30 15:20
Duplicate of https://github.com/kumahq/kuma/issues/5516
xref https://github.com/kumahq/kuma/issues/8119

**Closed by jakubdyszkiewicz** 2023-10-30 15:20 UTC
Labels: triage/pending, kind/feature
