### ISSUE TITLE
Surface / copy Service metadata (labels?) to service insights

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#6407] opened 2023-03-31 00:36 UTC
### Description

End-user request to propagate svc metadata on K8s to our service object so it appears and is filterable / searchable on the UI.

**Comment by jakubdyszkiewicz** [comment] 2023-04-03 14:23
Duplicate of https://github.com/kumahq/kuma/issues/6331

**Closed by jakubdyszkiewicz** 2023-04-03 14:23 UTC
Labels: triage/pending, kind/feature
