### ISSUE TITLE
TrafficMirror Policy

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma#680] opened 2020-04-15 14:46 UTC
```yaml
type: TrafficMirror
name: mirror-1
mesh: default
sources:
  - match:
      service: backend
      version: 1
destinations:
  - match:
      service: redis
      version: 5
conf:
  - amount: 25
    destination:
      service: redis
      version: 6
  - amount: 10
    destination:
      service: redis
      version: 2
```

**Comment by subnetmarco** [comment] 2020-05-07 16:44
In this issue we allow the user to duplicate traffic to multiple destinations concurrently. If this is not possible in Envoy, please take a look at this alternative proposal which only allows to duplicate traffic once at a time: https://github.com/Kong/kuma/issues/724

**Comment by lahabana** [comment] 2021-11-22 17:25
Dupe of #724

**Closed by lahabana** 2021-11-22 17:25 UTC
Labels: triage/duplicated, kind/feature, kind/design
