### ISSUE TITLE
kumactl inspect failing when running against global cluster

### ISSUE THREAD

**Issue by albertpx** [kumahq/kuma#6544] opened 2023-04-15 21:53 UTC
### What happened?

On a universal multi-zone cluster, when kumactl is configured to run against the global control plane, running the following command:
```
kumactl inspect zoneingress ingress-zone-instance-1 --type=config-dump
```
Returns the following error:
```
Error: Could not execute admin operation (Internal Server Error)
```

When checking the log of the global control plane, you can see the following error:
```
2023-04-11T19:11:30.902004000Z 2023-04-11T19:11:30.901Z ERROR   Could not execute admin operation       {"error": "instance not found", "errorVerbose": "instance not found\ngithub.com/kumahq/kuma/pkg/intercp/catalog.init\n\tgithub.com/kumahq/kuma/pkg/intercp/catalog/catalog.go:30\nruntime.doInit\n\truntime/proc.go:6230\nruntime.doInit\n\truntime/proc.go:6207\nruntime.doInit\n\truntime/proc.go:6207\nruntime.doInit\n\truntime/proc.go:6207\nruntime.doInit\n\truntime/proc.go:6207\nruntime.main\n\truntime/proc.go:233\nruntime.goexit\n\truntime/asm_amd64.s:1571
```

The command succeeds with no issues when running kumactl against the zone control plane of the ingress proxy.

**Comment by jakubdyszkiewicz** [comment] 2023-07-21 11:07
Hey, can you confirm this is also a problem in 2.3.0?

If you have CP in front of HTTP proxy then it could be this issue that was fixed and released https://github.com/kumahq/kuma/pull/6915

**Comment by michaelbeaumont** [comment] 2023-10-04 12:34
@albertpx Have you had a chance to check whether your issue's been resolved by the above fix?

**Comment by albertpx** [comment] 2023-10-04 13:29
Unfortunately, due to many issues we have stumbled upon, we have decided not to continue with Kuma. I do not have the environment to test it on anymore.

However, I gave clear instructions on how to replicate the issue. Perhaps someone else with universal multi zone environment can try it?

**Comment by slonka** [comment] 2023-10-09 11:04
I also feel like there is enough information. I'll try to reproduce this.

**Comment by slonka** [comment] 2023-10-09 11:54
I've run multizone setup locally:

Global:
```
KUMA_ENVIRONMENT=universal KUMA_MODE=global KUMA_MULTIZONE_GLOBAL_KDS_TLS_ENABLED=false KUMA_STORE_TYPE=memory ~/bin/kuma-2.4.2/bin/kuma-cp run
```

Zone1:
```
KUMA_ENVIRONMENT=universal KUMA_MODE=zone KUMA_MULTIZONE_ZONE_NAME=zone1 KUMA_API_SERVER_HTTP_PORT=15681 KUMA_API_SERVER_HTTPS_PORT=15682 KUMA_DIAGNOSTICS_SERVER_PORT=15680 KUMA_DP_SERVER_PORT=15678 KUMA_INTER_CP_SERVER_PORT=15683 KUMA_MONITORING_ASSIGNMENT_SERVER_PORT=15676 KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpc://localhost:5685 KUMA_STORE_TYPE=memory ~/bin/kuma-2.4.2/bin/kuma-cp run
```

Zone2:
```
KUMA_ENVIRONMENT=universal KUMA_MODE=zone KUMA_MULTIZONE_ZONE_NAME=zone2 KUMA_API_SERVER_HTTP_PORT=25681 KUMA_API_SERVER_HTTPS_PORT=25682 KUMA_DIAGNOSTICS_SERVER_PORT=25680 KUMA_DP_SERVER_PORT=25678 KUMA_INTER_CP_SERVER_PORT=25683 KUMA_MONITORING_ASSIGNMENT_SERVER_PORT=25676 KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpc://localhost:5685 KUMA_STORE_TYPE=memory ~/bin/kuma-2.4.2/bin/kuma-cp run
```

Ingress:
```
type: ZoneIngress
name: zoneingress-1
networking:
  address: my_address
  port: 10001
  advertisedAddress: my_address
  advertisedPort: 10000
```

```
~/bin/kuma-2.4.2/bin/kuma-dp run \
--proxy-type=ingress \
--cp-address=https://localhost:15678 \
--dataplane-token-file=ingress-token \
--dataplane-file=zone-ingress.yaml
```

Then running kumactl:
```
kumactl version
Client: Kuma 2.4.2
Server: Kuma 2.4.2
```

And getting the ingress (from global):
```
$ kumactl inspect zoneingress zone1.zoneingress-1 --type=config-dump | head -n 2
{
 "configs": [
```

And from zone:
```
kumactl inspect zoneingress zoneingress-1 | head -n 2
{
 "configs": [
```

@albertpx can you look through what I did and see anything missing?

**Comment by slonka** [comment] 2023-10-09 11:55
Also the error `instance not found` seems to indicate that there was a problem with the catalog 🤔

**Comment by slonka** [comment] 2023-11-27 13:02
@albertpx did you find time to check the way I reproduced this? also moving to triage since it does not look like there is much going on in this issue, might be closed

**Comment by jakubdyszkiewicz** [comment] 2024-01-15 15:52
> Triage: closing due to no activity

**Closed by jakubdyszkiewicz** 2024-01-15 15:52 UTC
Labels: triage/needs-information, kind/bug
