### ISSUE TITLE
UI and kumactl don't show specific zone-ingress resource

### ISSUE THREAD

**Issue by jamesdbloom** [kumahq/kuma#2596] opened 2021-08-18 11:47 UTC
### Summary

UI and kumactl don't show specific zone-ingress resource and return invalid not-found response.

### Steps To Reproduce

List zone ingresses using kumactl

```
$ kumactl get zone-ingresses
NAME                                AGE
ec2.kuma-zone-ingress-one.default   27m
ec2.kuma-zone-ingress-two.default   27m
```

List zone ingresses using kumactl with full yaml

```
$ kumactl get zone-ingresses -o yaml

items:
- availableServices:
  - instances: 1
    mesh: default
    tags:
      kuma.io/protocol: http
      kuma.io/service: testservice-one
      kuma.io/zone: ec2
  - instances: 1
    mesh: default
    tags:
      kuma.io/protocol: http
      kuma.io/service: testservice-two
      kuma.io/zone: ec2
  creationTime: "2021-08-18T11:08:31Z"
  modificationTime: "2021-08-18T11:08:31Z"
  name: ec2.kuma-zone-ingress-one.default
  networking:
    address: 10.4.56.40
    advertisedAddress: 52.49.135.214
    advertisedPort: 10000
    port: 10000
  type: ZoneIngress
  zone: ec2
- availableServices:
  - instances: 1
    mesh: default
    tags:
      kuma.io/protocol: http
      kuma.io/service: testservice-one
      kuma.io/zone: ec2
  - instances: 1
    mesh: default
    tags:
      kuma.io/protocol: http
      kuma.io/service: testservice-two
      kuma.io/zone: ec2
  creationTime: "2021-08-18T11:08:36Z"
  modificationTime: "2021-08-18T11:08:36Z"
  name: ec2.kuma-zone-ingress-two.default
  networking:
    address: 10.4.27.134
    advertisedAddress: 54.78.79.80
    advertisedPort: 10000
    port: 10000
  type: ZoneIngress
  zone: ec2
next: null
total: 2
```

Show specific zone ingresses using kumactl, this fail incorrect and also doesn't show in the GUI

```
$ kumactl get zone-ingress ec2.kuma-zone-ingress-one.default
Error: No resources found
```

<img width="1148" alt="Screenshot 2021-08-18 at 12 44 58" src="https://user-images.githubusercontent.com/733179/129892531-49ebb1d1-1cc0-4c74-8dcf-8262d615c7a0.png">

Zone ingress in visible from kubectl

```
$ kubectl -n default get zoneingresses.kuma.io
NAME                        AGE
ec2.kuma-zone-ingress-one   27m
ec2.kuma-zone-ingress-two   27m
```

Zone ingress in visible from kubectl and with full yaml detail

```
$ kubectl -n default get zoneingresses.kuma.io ec2.kuma-zone-ingress-one -o yaml
apiVersion: kuma.io/v1alpha1
kind: ZoneIngress
mesh: default
metadata:
  annotations:
    k8s.kuma.io/synced: "true"
  creationTimestamp: "2021-08-18T11:08:31Z"
  generation: 3
  name: ec2.kuma-zone-ingress-one
  namespace: default
  ownerReferences:
  - apiVersion: kuma.io/v1alpha1
    kind: Zone
    name: ec2
    uid: 47f8a0c7-6080-4d92-8208-ca308aa49d1a
  resourceVersion: "6947180"
  uid: 97eee1eb-372e-4196-bce2-57118440c837
spec:
  availableServices:
  - instances: 1
    mesh: default
    tags:
      kuma.io/protocol: http
      kuma.io/service: testservice-one
      kuma.io/zone: ec2
  - instances: 1
    mesh: default
    tags:
      kuma.io/protocol: http
      kuma.io/service: testservice-two
      kuma.io/zone: ec2
  networking:
    address: 10.4.56.40
    advertisedAddress: 52.49.135.214
    advertisedPort: 10000
    port: 10000
  zone: ec2
```

### Additional Details & Logs

- Version

Kuma: 1.2.3

- Error logs

Not captured

- Configuration

See YAML output above

- Platform and Operating System

EC2, CentOS 8

- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)

manual via systemctl

**Comment by lahabana** [comment] 2021-11-22 14:56
Closing in favour of #kumahq/kuma-gui#259

**Comment by lahabana** [comment] 2021-11-22 14:59
Actually keeping this open for the kumactl bit

**Comment by tomaszwylezek** [comment] 2021-12-02 13:16
Hi @jamesdbloom. 
I tried to reproduce it, but I failed - as it works for me. Please reopen the ticket if you are still experiencing an issue.

**Closed by tomaszwylezek** 2021-12-02 13:16 UTC
Labels: area/kumactl, area/multizone, triage/pending
