### ISSUE TITLE
Add ability to pass generic parameters to the Envoy command line

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2357] opened 2021-07-13 12:48 UTC
### Summary

I'd like to be able to pass any command line parameter to the envoy command line. For example, --concurrency or --drain-strategy. Any of these: https://www.envoyproxy.io/docs/envoy/latest/operations/cli

**Comment by jpeach** [comment] 2021-07-13 21:30
Duplicate of #1920. Please see the discussion there on which arguments can supportably be set.

**Closed by jpeach** 2021-07-13 21:30 UTC
