### ISSUE TITLE
Set owners for Secrets

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1137] opened 2020-11-09 14:25 UTC
### Summary

Currently, we set owners for all resources. For example, when TrafficPermission is created, its owner is the Mesh. When Mesh is deleted TrafficPermission is also deleted. Secrets should follow the same mechanism. Right now, we are deleting them explicitly when we are deleting the mesh.

**Comment by lahabana** [comment] 2021-12-01 10:12
Duplicate of #3276

**Closed by lahabana** 2021-12-01 10:12 UTC
Labels: area/kuma-cp, area/universal, kind/cleanup, kind/improvement
