### ISSUE TITLE
Create an optional installation path for the Gateway API controller

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3447] opened 2021-12-09 00:36 UTC
### Description

In Kubernetes clusters, create a way to optionally install the Gateway API ingress controller.

My preference is that this is installed as a separate component from kuma-cp so that 
* it can be truly optional and we don't accidentally assume it
* it can have separate RBAC (least privilege)

**Comment by jpeach** [comment] 2021-12-23 04:50
xref #3612

**Comment by lahabana** [comment] 2022-02-23 09:15
Duplicate of #3702

**Closed** 2022-02-23 09:15 UTC
Labels: area/k8s, triage/duplicated, kind/feature, area/gateway
