### ISSUE TITLE
Container with application is not able to communicate before sidecar is ready

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#5497] opened 2022-12-13 20:08 UTC
### Description

When deploying Kuma on Kubernetes we use IPtables to hijack traffic and route it through the sidecar. Sometimes the application might need to communicate with database/metrics just after starting but the sidecar might not be available. It might be problematic and block users from migration. 

**Possible solution** 
- we can use *postStart* and wait for sidecar to be ready [ref](https://thecloudblog.net/lab/kubernetes-container-lifecycle-events-and-hooks/)

**Comment by lahabana** [comment] 2022-12-13 20:41
Duplicate of https://github.com/kumahq/kuma/issues/2483

**Closed by lahabana** 2022-12-13 20:41 UTC
Labels: triage/duplicated, kind/bug
