### ISSUE TITLE
Improve xds.ResourceSet so that data layout is more straightforward

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6417] opened 2023-03-31 07:03 UTC
### Description

`xds.ResourceSet` was created before the plugin api.
The layout of the resources forced us to create a lot of utility methods (GatherListeners,GatherClusters...) to extract the right information. They all live in this package: https://github.com/kumahq/kuma/tree/master/pkg/plugins/policies/xds

https://github.com/kumahq/kuma/blob/afd4634bd5454c25140dfc8beea5e3ad07aca4cc/pkg/core/xds/resource.go#L65-L69

Should we evolve this datastructure so that it's populated in a way that is easily usable in plugins and get rid of this `Gather*` helpers?

**Comment by jakubdyszkiewicz** [comment] 2023-10-30 15:39
Duplicate of https://github.com/kumahq/kuma/issues/8123

**Closed by jakubdyszkiewicz** 2023-10-30 15:39 UTC
Labels: triage/accepted, kind/improvement, area/policies
