### ISSUE TITLE
Upgrade Kong version in kumactl install gateway

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#6749] opened 2023-05-11 16:39 UTC
### Description

We are using `kong/kong-gateway:2.5` while there is `3.2` available

xref: https://github.com/kumahq/kuma/issues/4888

**Comment by jakubdyszkiewicz** [comment] 2023-05-15 14:25
Duplicate of https://github.com/kumahq/kuma/issues/6750

**Closed by jakubdyszkiewicz** 2023-05-15 14:25 UTC
Labels: triage/pending, kind/improvement
