### ISSUE TITLE
Use consistent port (9901) for envoy admin api/console between k8s and universal

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1724] opened 2021-03-26 12:33 UTC
Currently the ports are different ... k8s uses the 9901 standard and universal uses 30001.

**Comment by subnetmarco** [comment] 2021-03-30 14:20
@kumahq/kuma-maintainers this should be an easy fix?

**Comment by jakubdyszkiewicz** [comment] 2021-07-02 12:09
I'd change this in the next major. Technically it's "internal" port, but just so we don't break something, let's do this in next major.

**Comment by lahabana** [comment] 2021-12-13 14:08
Duplicate of #3281

**Closed** 2021-12-13 14:08 UTC
Labels: triage/duplicated, kind/feature
