### ISSUE TITLE
kuma DP starts slower than application blocks application to work

### ISSUE THREAD

**Issue by daemon027** [kumahq/kuma#3628] opened 2021-12-28 02:34 UTC
### What happened?

I use kuma 1.4.0 and find kuma DP takes 3~4s to start while my APP takes 2s to start, my app can't work and keeps restarting until the kuma DP starts.

Something from the log:
kuma DP
```ShellSession
Args:
      run
      --log-level=info
      --concurrency=2
    State:          Running
      Started:      Fri, 24 Dec 2021 16:27:39 +0800
    Ready:          True
    Restart Count:  0
```

my APP
```ShellSession
Command:
      /app/xxxx
    State:          Running
      Started:      Fri, 24 Dec 2021 16:27:53 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 24 Dec 2021 16:27:40 +0800
      Finished:     Fri, 24 Dec 2021 16:27:40 +0800
    Ready:          True
    Restart Count:  2
```

Is there a way I can bypass DP when DP is NOT ready?

**Comment by lahabana** [comment] 2022-01-04 08:50
Duplicate of #2483

**Closed** 2022-01-04 08:51 UTC
Labels: triage/duplicated, kind/bug
