### ISSUE TITLE
Remove 'mesh' from Universal resource's primary key

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#7166] opened 2023-07-04 17:17 UTC
### Description

Primary keys are different for resources on Universal and Kubernetes:
* Universal: (name, namespace, mesh, type)
* Kubernetes: (name, namespace, kind)

Potentially this can result in inconsistent state when Global on Universal and Zone on k8s:

* Global(Universal):
```yaml
type: MeshTrafficPermission
name: allow-all
mesh: mesh-1
spec: {}
---
type: MeshTrafficPermission
name: allow-all
mesh: mesh-2
spec: {}
```

* Zone(Kubernetes):
```yaml
kind: MeshTrafficPermission
metadata:
  name: allow-all
  namespace: kuma-system
  labels:
    kuma.io/mesh: mesh-1
spec: {}
```
MeshTrafficPermission from mesh-2 is not synced to Zone because there is already MeshTrafficPermission with a key `(allow-all, kuma-system, MeshTrafficPermission)`.

One of the solutions is to remove `mesh` from Universal's primary key and force users to have unique policy names across all meshes. It's not ideal, but at least Universal and Kubernetes will be consistent.

**Comment by lahabana** [comment] 2023-07-05 12:39
Duplicate of #3837

One other option is to put at the end of the name a hash which is something like "zone-mesh" that way policies would also always fit with the number of characters.

Removing from the primary key makes it a little tricky as it would remove flexibility and be a breaking change.

**Closed** 2023-07-05 12:39 UTC
Labels: triage/duplicated, kind/bug
