### ISSUE TITLE
`MeshTimeout` incorrectly configures inbound `MeshGateway` listeners

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5555] opened 2022-12-23 14:55 UTC
### What happened?

The policy:
```yaml
kind: MeshTimeout
apiVersion: kuma.io/v1alpha1
metadata:
  namespace: kuma-system
  name: eg
spec:
  targetRef:
    kind: MeshService
    name: edge-gateway
  to:
    - targetRef:
        kind: MeshService
        name: frontend_kuma-demo_svc_8080
      default:
        http:
          streamIdleTimeout: 32s
```

sets `streamIdleTimeout` for the edge gateway listener. This listener is shared across all destination services so it's not correct to set it this way.

**Comment by jakubdyszkiewicz** [comment] 2023-01-03 14:54
> Triage: it's not clear yet what is the correct behaviour

**Comment by michaelbeaumont** [comment] 2023-01-03 15:07
For clarity, the issue is that `streamIdleTimeout` is an HTTP connection manager option that's normally set on outbound listeners. However there are no outbound listeners created for gateways. If we want to support `spec.targetRef.kind: MeshService` for both builtin gateway proxies and sidecar proxies we need to validate what kind of `Dataplane` `spec.targetRef` points to.

**Comment by lahabana** [comment] 2023-01-24 11:27
@michaelbeaumont sounds like you've fixed that no? Should we close this?

**Comment by michaelbeaumont** [comment] 2023-05-30 17:27
Yes, this has been fixed. Inbound listeners cannot be configured by `MeshTimeout`.

**Closed by michaelbeaumont** 2023-05-30 17:27 UTC
Labels: triage/accepted, kind/bug
