### ISSUE TITLE
Allow helm chart to add custom pod Annotations

### ISSUE THREAD

**Issue by sentinelleader** [kumahq/kuma#4367] opened 2022-05-26 17:47 UTC
### Description

The current helm chart doesnt allow users to add custom pod annotations to kuma pods. For example, if we are using a custom annotations for metric scraping, there is no way to set that via helm

**Comment by jakubdyszkiewicz** [comment] 2022-05-27 06:48
duplicate of https://github.com/kumahq/kuma/issues/4364

**Closed by jakubdyszkiewicz** 2022-05-27 06:48 UTC
Labels: triage/pending, kind/feature
