### ISSUE TITLE
Make init container ordering configurable

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#6531] opened 2023-04-13 22:47 UTC
### What happened?

Ideally this change (https://github.com/kumahq/kuma/pull/5857) should have made the init order configurable (first or last) as some init containers require the internet and there isn't a good answer for that right now.

**Comment by lahabana** [comment] 2023-04-14 12:08
Duplicate of #6082

**Closed by lahabana** 2023-04-14 12:08 UTC
Labels: triage/pending, kind/bug
