### ISSUE TITLE
Support host header rewrite for upstreams of the Kuma builtin gateway

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#5895] opened 2023-01-31 16:53 UTC
### Description

For external services which are themselves a load balancer (for example an K8s Ingress Controller) that can route requests using the host header, we need host headers to be swapped with the hostname of the upstream host chosen by the cluster manager, i.e. by setting the auto_host_rewrite on the route (on the MeshGatewayRoute resource).

**Comment by jakubdyszkiewicz** [comment] 2023-02-01 08:29
Related/duplicate of https://github.com/kumahq/kuma/issues/3921 ?
https://github.com/kumahq/kuma/pull/1635

**Comment by lahabana** [comment] 2023-03-14 17:29
Let's put it in both MeshHTTPRoute and MeshGatewayRoute

**Closed** 2023-03-31 09:29 UTC
Labels: triage/accepted, kind/feature
