### ISSUE TITLE
Extracting openapi schemas for Kuma CRDs

### ISSUE THREAD

**Issue by Revolyssup** [kumahq/kuma#3930] opened 2022-02-25 14:17 UTC
### Description

For extending support of Kuma using Meshery, the Meshery Adapter for Kuma is in dire need of openapi schemas for kuma CRDs.
CRDs that reside with kuma do not have schemas and they bypass kubernetes validation. 
Is there any way to extract those schemas for different CRDs?

**Comment by lahabana** [comment] 2022-02-25 14:22
xref: https://github.com/kumahq/kuma/issues/2107

**Comment by lahabana** [comment] 2022-02-25 14:24
Thanks for the report! This is something we're looking into. The way we setup things to make our Resources also work with Universal (non K8s) makes this tricky but we may have a path forward.

**Comment by lahabana** [comment] 2022-02-28 15:20
Dupe of #2107

**Closed** 2022-02-28 15:22 UTC
Labels: triage/duplicated, kind/feature
