### ISSUE TITLE
use existing cluster for global control plane

### ISSUE THREAD

**Issue by manju-rn** [kumahq/kuma#5093] opened 2022-10-05 05:02 UTC
### What happened?

I want to establish multi-cluster communication - service in 1 cluster calls the service in another.  So as I understand the control-plane from each of the cluster needs to call Global Control plane.  And the Global Plane requires its own cluster. Is there a way to use one of the cluster for Global Control Plane?  So, the global control plane and the local control plane resides in the same cluster

**Comment by lahabana** [comment] 2022-10-07 08:07
Duplicate of https://github.com/kumahq/kuma/issues/1496 . This is something that is planned. We need to migrate all policies to be namespaced first.

**Closed by lahabana** 2022-10-07 08:07 UTC
Labels: triage/duplicated, kind/bug
