### ISSUE TITLE
vagrant demo need to update kuma to 1.3.0

### ISSUE THREAD

**Issue by thatsk** [kumahq/kuma#2729] opened 2021-09-04 13:55 UTC
### Summary

we are still getting kuma 1.0.3 on vagrant demo.
please update it to 1.3.0

**Comment by thatsk** [comment] 2021-09-04 13:56
{code}
WARNING: You are using kumactl version 1.3.0 for Kuma, but the server returned version: Kuma 1.0.3
MESH      NAME         TAGS                                                       AGE
default   backend      kuma.io/protocol=http kuma.io/service=backend version=v0   2h
default   backend-v1   kuma.io/protocol=http kuma.io/service=backend version=v1   2h
default   frontend     kuma.io/protocol=http kuma.io/service=frontend             2h
default   kong         kuma.io/service=kong                                       1h
default   postgresql   kuma.io/service=postgresql                                 2h
default   redis        kuma.io/service=redis                                      2h
{code}

**Comment by jpeach** [comment] 2021-09-06 06:04
Thanks @thatsk. Marking this as a duplicate of kumahq/kuma-demo#121.

**Closed by jpeach** 2021-09-06 06:04 UTC
