### ISSUE TITLE
Get rid of `api/Makefile`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#2621] opened 2021-08-20 17:08 UTC
James removed the multiple go modules we had and it would make sense to now get rid of this extra `Makefile` and the `api_check` circleci job.

This would mean that there's a single Makefile for all of the repo which would be nicer to newcomers.

**Comment by jpeach** [comment] 2021-08-20 23:37
Duplicate of https://github.com/kumahq/kuma/issues/2495

**Closed** 2021-08-22 22:10 UTC
Labels: good first issue, ci
