### ISSUE TITLE
ZoneIngress configdump from global fails

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5217] opened 2022-08-07 07:32 UTC
### What happened?

On kuma 1.7.0 while kds is working I can’t get an ingress configDump. The logs show this error:

`2022-08-02T16￼22.071Z	ERROR	Could not get config_dump	{"error": "error response from Zone CP: unable to send GET to config_dump: Get \"https://172.31.46.159:9901/config_dump\": dial tcp 172.31.46.159:9901: i/o timeout", "errorVerbose": "error response from Zone CP: unable to send GET to config_dump: Get \"https://172.31.46.159:9901/config_dump\": dial tcp 172.31.46.159:9901: i/o timeout\http://ngithub.com/kumahq/kuma/pkg/envoy/admin.(*kdsEnvoyAdminClient).ConfigDump\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220613151446-fa5bf900a665/pkg/envoy/admin/kds_client.go:61\http://ngithub.com/kumahq/kuma/pkg/api-server.inspectZoneIngressXDS.func1\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220613151446-fa5bf900a665/pkg/api-server/inspect_endpoints.go:399\http://ngithub.com/emicklei/go-restful.(*FilterChain).ProcessFilter\n\t/home/circleci/.go_workspace/pkg/mod/github.com/emicklei/go-restful@v2.15.0+incompatible/filter.go:21\http://ngithub.com/emicklei/go-restful.CrossOriginResourceSharing.Filter\n\t/home/circleci/.go_workspace/pkg/mod/github.com/emicklei/go-restful@v2.15.0+incompatible/cors_filter.go:40\http://ngithub.com/emicklei/go-restful.(*FilterChain).ProcessFilter\n\t/home/circleci/.go_workspace/pkg/mod/github.com/emicklei/go-restful@v2.15.0+incompatible/filter.go:19\http://ngithub.com/kumahq/kuma/pkg/plugins/authn/api-server/tokens.UserTokenAuthenticator.func1\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220613151446-fa5bf900a665/pkg/plugins/authn/api-server/tokens/authenticator.go:34\http://ngithub.com/emicklei/go-restful.(*FilterChain).ProcessFilter\n\t/home/circleci/.go_workspace/pkg/mod/github.com/emicklei/go-restful@v2.15.0+incompatible/filter.go:19\http://ngithub.com/kumahq/kuma/pkg/util/prometheus.MetricsHandler.func1.1\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220613151446-fa5bf900a665/pkg/util/prometheus/gorestful_middleware.go:21\http://ngithub.com/slok/go-http-metrics/middleware.Middleware.Measure\n\t/home/circleci/.go_workspace/pkg/mod/github.com/slok/go-http-metrics@v0.10.0/middleware/middleware.go:117\http://ngithub.com/kumahq/kuma/pkg/util/prometheus.MetricsHandler.func1\n\t/home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220613151446-fa5bf900a665/pkg/util/prometheus/gorestful_middleware.go:20\http://ngithub.com/emicklei/go-restful.(*FilterChain).ProcessFilter\n\t/home/circleci/.go_workspace/pkg/mod/github.com/emicklei/go-restful@v2.15.0+incompatible/filter.go:19\http://ngithub.com/emicklei/go-restful.(*Container).dispatch\n\t/home/circleci/.go_workspace/pkg/mod/github.com/emicklei/go-restful@v2.15.0+incompatible/container.go:291\nnet/http.HandlerFunc.ServeHTTP\n\t/home/circleci/go/src/net/http/server.go:2084\nnet/http.(*ServeMux).ServeHTTP\n\t/home/circleci/go/src/net/http/server.go:2462\nnet/http.serverHandler.ServeHTTP\n\t/home/circleci/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/home/circleci/go/src/net/http/server.go:1966\nruntime.goexit\n\t/home/circleci/go/src/runtime/asm_amd64.s:1571"} `

**Comment by kleinfreund** [comment] 2022-11-02 16:03
**Triage**: Pretty likely to be a duplicate of https://github.com/kumahq/kuma/issues/5080.

**Closed by kleinfreund** 2022-11-02 16:03 UTC
Labels: triage/accepted, kind/bug
