### ISSUE TITLE
Favor endpoints from the same locality, while distributing traffic across multiple Kuma zones

### ISSUE THREAD

**Issue by sayap** [kumahq/kuma#5196] opened 2022-10-24 10:04 UTC
### Description

From https://kuma.io/docs/1.8.x/deployments/multi-zone/#about

> For load-balancing the zone ingress endpoints are weighted with the number of instances running behind them (.i.e: a zone with 2 instances will receive twice more traffic than a zone with 1 instance), you can also favor local traffic with [localityAware load-balancing](https://kuma.io/docs/1.8.x/policies/locality-aware.html).

Currently, it is an either-or situation, either we get locality-aware routing to reduce cross-region/cross-zone data transfer cost, or we can distribute traffic seamlessly across multiple Kuma zones to increase resilience without config overhead.

Both are desirable features, and I think we can get both if #1111 didn't hardcode `priorityLocal` and `priorityRemote`? i.e. envoy locality-aware routing should work independently of how a service is distributed across Kuma zones.

**Comment by jakubdyszkiewicz** [comment] 2022-10-24 14:08
Thanks for the report. This is duplicate of https://github.com/kumahq/kuma/issues/2689

**Closed by jakubdyszkiewicz** 2022-10-24 14:08 UTC
Labels: triage/pending, kind/feature
