### ISSUE TITLE
Remove install gateway from kumactl

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#6750] opened 2023-05-11 16:44 UTC
### What happened?

When installing kong-enterprise with kumactl `kumactl install gateway kong-enterprise` user must provide a path to the license. If the license has whitespace/newlines installation fails with the error

```
Error: Failed to sort resources by kind: YAML parse error on manifest-15: error converting YAML to JSON: yaml: line 23: did not find expected key
```

There are 2 options
* remove white signs and inline string in kumactl
* clarify in docs

Update(triage): we should delete this command. HELM should be the way to install this.

**Comment by jakubdyszkiewicz** [comment] 2023-05-15 14:26
> Triage: Add docs on how to install Kong Gateway via HELM

**Comment by lahabana** [comment] 2024-09-19 12:35
Duplicate of https://github.com/kumahq/kuma/issues/5896

**Closed by lahabana** 2024-09-19 12:35 UTC
Labels: triage/accepted, kind/bug
