### ISSUE TITLE
http requestTimeout policy should accept 0s

### ISSUE THREAD

**Issue by jgrund** [kumahq/kuma#3629] opened 2021-12-31 19:41 UTC
### What happened?

It is not currently possible to set the `requestTimeout` policy to `0s`, which is a [valid entry](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout) for this field.

In addition, this timeout appears to [default to 15 seconds](https://www.envoyproxy.io/docs/envoy/v1.18.2/faq/configuration/timeouts.html?highlight=request_timeout#route-timeouts), so it's not sufficient to simply omit the field if we want to disable this timeout.

**Comment by lahabana** [comment] 2022-01-03 15:04
Is this inbound, outbound or both?

**Comment by jgrund** [comment] 2022-01-03 15:30
Hi @lahabana trying to set `requestTimeout` to `0s` for this policy results in an error:

https://kuma.io/docs/1.4.1/policies/timeout/

Simply removing the check allows it to work:

```diff
diff --git a/pkg/core/resources/apis/mesh/timeout_validator.go b/pkg/core/resources/apis/mesh/timeout_validator.go
index acc4f83da..44074e0f5 100644
--- a/pkg/core/resources/apis/mesh/timeout_validator.go
+++ b/pkg/core/resources/apis/mesh/timeout_validator.go
@@ -72,7 +72,6 @@ func (t *TimeoutResource) validateConfHttp(path validators.PathBuilder, conf *me
 		err.AddViolationAt(path, "at least one timeout in section has to be defined")
 		return
 	}
-	err.Add(validateDuration_GreaterThan0OrNil(path.Field("requestTimeout"), conf.RequestTimeout))
 	err.Add(validateDuration_GreaterThan0OrNil(path.Field("idleTimeout"), conf.IdleTimeout))
 	return
 }
```

> Is this inbound, outbound or both?

I *think* outbound; the policy value ultimately gets set on config.route.v3.RouteAction (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout)

**Comment by lahabana** [comment] 2022-02-28 15:19
Dupe of: #3934

**Comment by lahabana** [comment] 2022-02-28 15:19
xref #3934

**Comment by lobkovilya** [comment] 2022-07-05 08:24
Fixed in https://github.com/kumahq/kuma/pull/4365

**Closed by lobkovilya** 2022-07-05 08:24 UTC
Labels: triage/accepted, kind/bug
