### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: protocol error

### ISSUE THREAD

**Issue by sai-ns** [kumahq/kuma#4536] opened 2022-06-30 18:56 UTC
### What happened?

We have a Java Spring boot app deployed on AKS cluster that in response provides a json object. App works fine without Kuma but as soon as Kuma is enabled, urls throws an upstream error and reason being protocol error. I can say, Kuma in general is working as we have other apps on the cluster that are working as expected.
Been trying to troubleshoot for a while but gone no where with it. 
Any insights on how to troubleshoot or if there is anything that needs to be fixed in Kuma. 
I see 502 Bad gateway error when I do a curl on the endpoint, at least from what I understood(could be wrong as well) Kuma is not liking the json response from the backend and throwing a 502.

**Comment by jakubdyszkiewicz** [comment] 2022-07-01 08:36
Hey,
thanks for the report.

reading the description I assume the application is just an HTTP app.
Is it marked as HTTP app? https://kuma.io/docs/1.7.x/policies/protocol-support-in-kuma
Does it handle TLS on its own?
Do you use mTLS in Kuma?

**Comment by jakubdyszkiewicz** [comment] 2022-07-04 13:57
Can you please check if it works with protocol TCP? Remove `8080.service.kuma.io/protocol: http` and set `appProtocol` to `tcp`.

Do you use multizone or standalone deployment?
How do you consume this application? Is the client an Ingress (nginx/kong)?
If you can, please enable Envoy debug logs (port forward 9901 and `curl -XPOST localhost:9901/logging?level=debug`) to client + server and send us logs. Thank you.

**Comment by sai-ns** [comment] 2022-07-04 17:06
It is working with TCP protocol. Below is how service definition looks like now
~~~
apiVersion: v1
kind: Service
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    argocd.argoproj.io/instance: APPNAME-nonprod
    backstage.io/kubernetes-id: APPNAME
  name: APPNAME-nonprod
  namespace: APP-nonprod
  ownerReferences:
  - apiVersion: CRD/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: WebApp
    name: APPNAME-nonprod
spec:
  clusterIP: 192.168.252.162
  clusterIPs:
  - 192.168.252.162
  ports:
  - appProtocol: tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: APPNAME-nonprod
  sessionAffinity: None
  type: ClusterIP
~~~
It is a multizone deployment with one global and 2 remote CPs. 
We access the application via Ingress nginx.
I will send debug logs soon but wanted to let you know that app is working as expected when using TCP protocol.

**Comment by jakubdyszkiewicz** [comment] 2022-07-12 08:09
Hey, thanks for the logs. I looked at this and this line is a cause of the error
```
[2022-07-05 15:11:00.574][38][debug][client] [source/common/http/codec_client.cc:149] [C120370] Error dispatching received data: http/1.1 protocol error: unsupported transfer encoding
```
which is most likely caused by the invalid value of `transfer-encoding` header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

can you please post response headers from the application protocol set to TCP or run without Envoy?

**Comment by lahabana** [comment] 2022-07-15 07:28
@jakubdyszkiewicz you also need the request headers no?

**Comment by jakubdyszkiewicz** [comment] 2022-07-18 10:24
`transfer-encoding` should be set in response headers. On a request, you can set [`accept-encoding`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding).

We cannot see transfer-encoding here, so either Chrome hides it somehow or it's just not set for this request.
We can also look into accept-encoding in requests.

Do you maybe set transfer-encoding or accept-encoding in your application?

**Comment by sai-ns** [comment] 2022-07-18 18:40
I do see accept-encoding in the request(below) but don't see transfer-encoding in chrome as well as curl. I am checking with the developer if he set something in app.
![image](https://user-images.githubusercontent.com/59936125/179580089-29790f2b-877e-4866-a77a-6fd80c3884d8.png)

**Comment by sai-ns** [comment] 2022-07-22 17:15
Sorry, took a while to respond but after checking with the developers, they are not setting anything in the application.

**Comment by lahabana** [comment] 2022-07-27 14:33
Hi @sai-ns we're running out of ideas. Is there anyway to reproduce this in an environment we could try out with? (Like an clean EKS or k3d cluster maybe?)

If you do would love to know how to repro (different deployments, kuma version and install flags...).

**Comment by sai-ns** [comment] 2022-07-27 17:31
Sorry I didn't get your question if you are asking me to reproduce in a different cluster(clean) or if it is possible for you to reproduce in your environment?

I can try to deploy this to a new AKS cluster and reproduce if that's what you are asking.

**Comment by lahabana** [comment] 2022-07-28 15:05
That's right @sai-ns try to reproduce in a minimal environment and then tell us what you did so we can reproduce ourselves.

**Comment by lukidzi** [comment] 2022-08-09 06:10
@sai-ns Hi. Have you had time to try to reproduce it?

**Comment by sai-ns** [comment] 2022-08-11 15:58
@lukidzi sorry I haven't gotten a chance yet but will definitely have time next week to reproduce on a different cluster.

**Comment by lahabana** [comment] 2022-08-25 13:01
@sai-ns any updates? We're struggling to reproduce

**Comment by sai-ns** [comment] 2022-08-26 20:01
I was able to reproduce the same error on a different new cluster with similar setup. We use a K8s custom resource definition which uses an operator and spins up 1 deployment, 2 services(1 clusterIP and 1 external LB for Kuma) and an ingress resource. 
I looked at the deployment and don't see anything that stands out or different than any standard deployment. Two services are same as what I posted earlier(3rd comment of this conversation). Ingress manifest is below 
~~~
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
  name: 
  namespace: 
spec:
  rules:
  - host: APPURL
    http:
      paths:
      - backend:
          service:
            name: EXTERNALSVC-externalname
            port:
              number: 80
        path: /
        pathType: Prefix
~~~

Please let me know if you need any more information. With this setup, I am able to reproduce the protocol error and make it work by making the service app protocol to tcp

**Comment by lukidzi** [comment] 2022-09-20 10:18
@sai-ns Do you have time to provide some sample application that allows reproducing the problem?

**Comment by michaelbeaumont** [comment] 2022-10-24 11:17
@sai-ns Any luck? We'd need the most basic set of k8s resources and application with which you can reproduce, so likely without using an operator or Ingress resources.

**Comment by slonka** [comment] 2022-10-31 13:47
@sai-ns - any update on this?

**Comment by jakubdyszkiewicz** [comment] 2022-12-12 15:37
> Triage: closing for now, please reopen if we can get more information. Thank you

**Closed by jakubdyszkiewicz** 2022-12-12 15:37 UTC
Labels: triage/pending, kind/bug
