### ISSUE TITLE
Share parsing code and config structures between `app/cni` and `pkg/transparentproxy`

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#8320] opened 2023-11-10 17:28 UTC
### Description

Kuma CNI supports the same list of annotations as the Kuma Init container. We can share the code, to reduce duplication and potentially losing functionality for either component.

Kuma CNI annotations: https://github.com/kumahq/kuma/blob/16fdff35ddef063e9e466a0c0396c1f79df7e95d/app/cni/pkg/cni/annotations.go#L20

Transparent proxy annotations: https://github.com/kumahq/kuma/blob/1633d34ad116dd1e618f4a27dd1526f5ff7d8bde/pkg/transparentproxy/kubernetes/kubernetes.go#L48

**Comment by lahabana** [comment] 2023-11-13 08:39
Duplicate of: https://github.com/kumahq/kuma/issues/8324

**Closed by lahabana** 2023-11-13 08:39 UTC
Labels: triage/pending, kind/improvement
