### ISSUE TITLE
Use CLA cache efficiently for all types of proxies

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#7599] opened 2023-08-25 16:17 UTC
### Description

We have at least 3 generators that are capable of using CLA cache:
1. DPP (already use CLA cache)
2. Builtin Gateway (already use CLA cache)
3. Zone Ingress (doesn't use CLA cache)

The problem is these generators name the clusters differently:
1. DPP – https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/outbound_proxy_generator.go#L374
2. Builtin Gateway – https://github.com/kumahq/kuma/blob/master/pkg/xds/envoy/tags/match.go#L20
3. Zone Ingress – https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/zoneproxy/generator.go#L24

Different cluster names lead to different keys in the CLA cache, and because of that, the cache is not as efficient as it could be.

**Comment by lahabana** [comment] 2023-10-11 14:13
@lukidzi you may be interested in this too

**Comment by michaelbeaumont** [comment] 2024-01-10 13:36
Update: we now name dataplane and gateway clusters the same way.

**Comment by lahabana** [comment] 2024-05-22 15:14
Duplicate of #8124 a generic cache across DPPs should cover different proxy types

**Closed by lahabana** 2024-05-22 15:14 UTC
Labels: triage/accepted, kind/improvement
