### ISSUE TITLE
Kuma-metrics Grafana init-plugins container error 

### ISSUE THREAD

**Issue by jondkelley** [kumahq/kuma#4448] opened 2022-06-08 19:53 UTC
### What happened?

This is a revival of https://github.com/kumahq/kuma/issues/2767

Seems to be happening on our version of Kuma 1.6.0 but the steps to reproduce are identical. We get things working if we disable mesh TLS (i.e. omitting `mesh.spec.tls` settings) and disable the sidecar on metrics, but can't reach envoy once TLS is enabled for the sidecars mesh.

> ### Summary

Used kumactl version 1.6.0 to generate a kuma-metrics yaml file.  After applying the kuma-metrics yaml, the grafana pod's init-plugins container errors with, `wget: bad address 'github.com`. The container will stay in CrashLoopBackOff status, never coming up.

Disabling the Kuma sidecar injection will allow the container to reach github, but then the grafana pod is outside of the mesh. This makes mTLS impossible to enable `mesh` spec.mtls for envoy.

> 
> ### Steps To Reproduce
> 1. Generate a kuma-mrtrics yaml using `./kumactl install metrics > kuma-metrics-master.yaml`
> 2. Apply the yaml `kubectl apply -f kuma-metrics-master.yaml`
> 
> ### Additional Details & Logs
> # Versions

AWS Kubernetes version: v1.22.6-eks-7d68063

>
> ## Configurations
> # Mesh
```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  annotations:
    k8s.kuma.io/mesh-defaults-generated: "true"
  creationTimestamp: "2022-06-08T13:21:11Z"
  generation: 6
  name: default
  resourceVersion: "214884573"
  uid: f4f1288c-3267-4998-bd99-f2b3a8788095
spec:
  metrics:
    backends:
    - conf:
        path: /metrics
        port: 5670
        skipMTLS: false
        tags:
          kuma.io/service: dataplane-metrics
      name: prometheus-1
      type: prometheus
    enabledBackend: prometheus-1
  mtls:
    backends:
    - conf:
        caCert:
          RSAbits: 2048
          expiration: 10y
      dpCert:
        rotation:
          expiration: 1d
      name: ca-1
      type: builtin
    enabledBackend: ca-1
```
> 
> # Kuma-metrics namespace
```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"kuma.io/mesh":"default"},"labels":{"kuma.io/sidecar-injection":"enabled"},"name":"kuma-metrics"}}
    kuma.io/mesh: default
  creationTimestamp: "2022-06-08T17:52:03Z"
  labels:
    kubernetes.io/metadata.name: kuma-metrics
    kuma.io/sidecar-injection: enabled
  name: kuma-metrics
  resourceVersion: "215216527"
  uid: d58b4b0e-3371-4664-a1b5-27d408d352a7
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```
> 
> # Kuma traffic routes
```yaml
apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  creationTimestamp: "2022-06-08T13:21:12Z"
  generation: 1
  name: route-all-default
  ownerReferences:
  - apiVersion: kuma.io/v1alpha1
    kind: Mesh
    name: default
    uid: f4f1288c-3267-4998-bd99-f2b3a8788095
  resourceVersion: "214589365"
  uid: b362126d-1136-46ec-b048-4bb0a2039421
spec:
  conf:
    destination:
      kuma.io/service: '*'
    loadBalancer:
      roundRobin: {}
  destinations:
  - match:
      kuma.io/service: '*'
  sources:
  - match:
      kuma.io/service: '*'
```

> ### Kuma-metrics yaml file used
[metrics.yaml.txt](https://github.com/kumahq/kuma/files/8865507/metrics.yaml.txt)

**Comment by jondkelley** [comment] 2022-06-08 19:56
The previously mentioned issue https://github.com/kumahq/kuma/issues/2767 was closed because `ExternalService` claimed to fix it, but I've tried an ExternalService config and it doesn't work. 

I don't think ExternalService will particularly fix anything...... the metrics INIT sidecar will try to start _**before**_ kuma-sidecar / kuma-dp does.. and should reach github without using envoy (unless iptables redirects make that impossible.)

Here's the `ExternalService` I tried:
```
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: github
spec:
  networking:
    address: github.com:443
    tls:
      enabled: true
  tags:
    kuma.io/protocol: http
    kuma.io/service: github
    type: github
```

**Comment by johnharris85** [comment] 2022-06-12 17:22
I think you're using the CNI plugin right (based on our conversations in Slack?). If so, there are only limited solutions to this. If you were using our init container to program iptables, we inject _after_ other init containers, so you wouldn't have this issue (but that init container obviously wouldn't be subject to any mesh policies). There is an issue open for being able to selectively decide where our init injects in the list, but that's not really relevant here.

Because of the CNI, by the time the grafana init comes to start, iptables has already been programmed to redirect traffic to the sidecar, which isn't up until after the init, so we're stuck. The only 2 (assuming you need to keep CNI) options here are:

- Configure the grafana init to run as UID/UID 5678. This is the same UID/GID as our sidecar and that traffic is excluded from the iptables redirection rules.
- Configure the `traffic.kuma.io/exclude-outbound-ports` annotation to not capture traffic for the port you're going out to. In this case, 443, but that's probably not desirable as then we're not going to enforce anything going out on that port which is probably, uh, most things.

Unfortunately the main issue here is Kubernetes lack of first-class support / definition of init & sidecar containers and ordering. There's no real way out of it :(

**Comment by lahabana** [comment] 2022-06-13 14:10
Triage: maybe the plugin should be published as a docker image. This would fix the downloading problem and still be able to run as an init-container in both envs?

**Comment by lahabana** [comment] 2022-10-05 08:58
Closing as duplicate of: https://github.com/kumahq/kuma-grafana-datasource/issues/127

**Closed by lahabana** 2022-10-05 08:58 UTC
Labels: triage/duplicated, kind/bug
